In [1]:
import spacy

In [2]:
import pandas as pd

In [3]:
nlp = spacy.load('en_core_web_sm')

In [4]:
emma = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
spacy_docs = nlp(emma)

In [6]:
print(emma)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [7]:
pos_docs = pd.DataFrame(columns = ["tokens", "pos_tag"])

In [11]:
for token in spacy_docs:
    pos_docs = pd.concat([pos_docs, pd.DataFrame.from_records([{"tokens": token.text, "pos_tag": token.pos_}])], ignore_index = True)

In [12]:
pos_docs.head(15)

         tokens pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [13]:
pos_docs_counts = pos_docs.groupby(['tokens', 'pos_tag']).size().reset_index(name = "counts").sort_values(by = 'counts', ascending = False)

In [14]:
pos_docs_counts.head(15)

        tokens pos_tag  counts
88          of     ADP      14
49         had     AUX       9
54         her    PRON       9
111        the     DET       8
6          and   CCONJ       8
0            a     DET       6
114         to    PART       5
61          in     ADP       4
13        been     AUX       4
120       very     ADV       4
48   governess    NOUN       3
46      friend    NOUN       3
125       with     ADP       2
5           an     DET       2
130      years    NOUN       2

In [16]:
pos_tags_grouped = pos_docs_counts.groupby(['pos_tag'])['tokens'].count().sort_values(ascending = False)

In [17]:
pos_tags_grouped.head(15)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
NUM       3
SCONJ     3
PART      1
Name: tokens, dtype: int64

In [21]:
nouns = pos_docs_counts[pos_docs_counts.pos_tag == "NOUN"][0:20]

In [22]:
nouns

          tokens pos_tag  counts
48     governess    NOUN       3
46        friend    NOUN       3
130        years    NOUN       2
35          emma    NOUN       2
28     daughters    NOUN       2
103      sisters    NOUN       2
82        mother    NOUN       2
89        office    NOUN       1
78      mistress    NOUN       1
75      mildness    NOUN       1
94        period    NOUN       1
95         place    NOUN       1
96   remembrance    NOUN       1
129        world    NOUN       1
126        woman    NOUN       1
121          vex    NOUN       1
109       temper    NOUN       1
108      taylors    NOUN       1
100       shadow    NOUN       1
97     restraint    NOUN       1

In [23]:
adverbs = pos_docs_counts[pos_docs_counts.pos_tag == "PROPN"][0:7]

In [24]:
adverbs

         tokens pos_tag  counts
76         miss   PROPN       2
107      taylor   PROPN       2
83           mr   PROPN       1
128  woodhouses   PROPN       1
127   woodhouse   PROPN       1
36         emma   PROPN       1