In [1]:
import spacy

In [2]:
import pandas as pd

In [3]:
nlp = spacy.load("en_core_web_sm")

In [6]:
para = "Google DeepMind is placing greater emphasis on the ethical development of artificial intelligence by integrating philosophers and ethics researchers into its AI teams. One of the key figures is philosopher Iason Gabriel, who works on ensuring that advanced AI systems are not only powerful but also aligned with human values. His work focuses on issues such as fairness, accountability, transparency, and the social impact of AI. As AI models become more capable, experts argue that technical improvements alone are not enough. Developers must also consider how AI affects society, employment, privacy, and decision-making. Google DeepMind believes that combining philosophy with computer science can help create AI systems that are safer, more reliable, and beneficial for everyone. This reflects a growing trend across the AI industry to prioritize responsible AI development alongside rapid technological innovation."

In [7]:
para

'Google DeepMind is placing greater emphasis on the ethical development of artificial intelligence by integrating philosophers and ethics researchers into its AI teams. One of the key figures is philosopher Iason Gabriel, who works on ensuring that advanced AI systems are not only powerful but also aligned with human values. His work focuses on issues such as fairness, accountability, transparency, and the social impact of AI. As AI models become more capable, experts argue that technical improvements alone are not enough. Developers must also consider how AI affects society, employment, privacy, and decision-making. Google DeepMind believes that combining philosophy with computer science can help create AI systems that are safer, more reliable, and beneficial for everyone. This reflects a growing trend across the AI industry to prioritize responsible AI development alongside rapid technological innovation.'

In [8]:
docs = nlp(para)

In [9]:
df_docs = pd.DataFrame(columns = ('tokens', 'pos_tag'))

In [10]:
df_docs.head()

Empty DataFrame
Columns: [tokens, pos_tag]
Index: []

In [11]:
for token in docs:
    df_docs = pd.concat([df_docs, pd.DataFrame.from_records([{'tokens': token.text, 'pos_tag': token.pos_}])], ignore_index=True)

In [13]:
df_docs.head(20)

          tokens pos_tag
0         Google   PROPN
1       DeepMind   PROPN
2             is     AUX
3        placing    VERB
4        greater     ADJ
5       emphasis    NOUN
6             on     ADP
7            the     DET
8        ethical     ADJ
9    development    NOUN
10            of     ADP
11    artificial     ADJ
12  intelligence    NOUN
13            by     ADP
14   integrating    VERB
15  philosophers    NOUN
16           and   CCONJ
17        ethics    NOUN
18   researchers    NOUN
19          into     ADP

In [15]:
df_docs_counts = df_docs.groupby(['tokens', 'pos_tag']).size().reset_index(name = "counts").sort_values(by = "counts", ascending = False)
df_docs_counts.head(20)

          tokens pos_tag  counts
0              ,   PUNCT      10
3             AI   PROPN       8
2              .   PUNCT       7
99           the     DET       4
22           and   CCONJ       4
98          that   SCONJ       3
23           are     AUX       3
73            of     ADP       3
74            on     ADP       3
105         with     ADP       2
21          also     ADV       2
70          more     ADV       2
93       systems    NOUN       2
72           not    PART       2
5       DeepMind   PROPN       2
39   development    NOUN       2
8         Google   PROPN       2
64            is     AUX       2
78    philosophy    NOUN       1
75          only     ADV       1

In [16]:
nouns = df_docs_counts[df_docs_counts.pos_tag == "NOUN"][0:25]

In [17]:
nouns

             tokens pos_tag  counts
93          systems    NOUN       2
39      development    NOUN       2
78       philosophy    NOUN       1
77     philosophers    NOUN       1
68           making    NOUN       1
69           models    NOUN       1
65           issues    NOUN       1
62     intelligence    NOUN       1
60       innovation    NOUN       1
86      researchers    NOUN       1
94            teams    NOUN       1
106            work    NOUN       1
103          values    NOUN       1
102           trend    NOUN       1
101    transparency    NOUN       1
82          privacy    NOUN       1
91          society    NOUN       1
89          science    NOUN       1
58     improvements    NOUN       1
59         industry    NOUN       1
57           impact    NOUN       1
14   accountability    NOUN       1
6        Developers    NOUN       1
49          figures    NOUN       1
48         fairness    NOUN       1